name: Jisu ECR Workflow
on: 
  push:
    brances: [main]
    paths-ignore:
    - '.github/workflows/'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

#### AWS Credentials Setting
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

#### ECR Login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#### Docker Build Set Up
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#### 이미지 태그에 삽입할 Env 생성 (Branch Name)
      - name: Get current branch name
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

#### 이미지 태그에 삽입할 Env 생성 (빌드 TimeStamp)
      - name: Get current timestamp
        run: echo "timestamp=$(TZ=Asia/Seoul date +'%Y%m%d')" >> $GITHUB_ENV

#### 컨테이너 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: DockerFile/Dockerfile
          push: true
          tags: |
            559394926122.dkr.ecr.ap-northeast-2.amazonaws.com/jisu:jisu-was-${{ env.branch_name }}-${{ env.timestamp }}
            559394926122.dkr.ecr.ap-northeast-2.amazonaws.com/jisu:latest


  

